### ISSUE TITLE
Could we implement the model to binocular vision ?

### ISSUE THREAD

**Issue by PhuDoTuong** [gkaguirrelab/gkaModelEye#35]
Dear Professor Geoffrey K Aguirre,

My name is Phu Do-Tuong, I am a master student in the Department of Biomedical Engineering, the Faculty of Applied Sciences, Ho Chi Minh City University of Technology - VNU HCMC.

Thank you for your fantastic-open-source work. Could we implement the model to binocular vision? 

Student name,
 Phu Do-Tuong

**Comment by gkaguirre** [comment]
Hello Phu. I expect that the model could be extended to capture aspects of binocular vision. Are you asking for advice on how to do this? Or are you perhaps requesting that a particular feature be added to the model?

**Comment by PhuDoTuong** [comment]
Dear Professor Geoffrey K Aguirre,

Sorry for my late response and unclear question. I am particular interested in implicit calibration methods for remote eye trackers. The main idea for these methods (the paper [1][2], for instance) is that visual axises from both eyes are converged on the interactive surface(s).

These methods usually implement Listing's law, but it probably is appropriate for distant target, monocular vision and upright state of the head as E. D. Guestrin illustrated in the paper [3]. I found that you also implement 2 version of Listing's law (the old one from Wong, Agnes MF's paper and the new one from Nakayama, K., K. Ciuffreda, and C. Schor's paper). As I know you really busy, I just ask that does the model be appropriate for binocular vision in terms of Listing's law?

Student name
Phu Do-Tuong

[1] D. Model and M. Eizenman, "User-calibration-free remote gaze estimation 
system," in Proceedings of the 2010 Symposium on Eye-Tracking Research & 
Applications, Austin, 2010.
[2] Nagamatsu et al., "Calibration-free gaze tracking using a binocular 3D eye 
model," in CHI '09 Extended Abstracts on Human Factors in Computing 
Systems, Boston, 2009.
[3] Guestrin, Elias D., and Moshe Eizenman. "Listing's and Donders' laws and the estimation of the point-of-gaze." Proceedings of the 2010 Symposium on Eye-Tracking Research & Applications. 2010.

**Comment by gkaguirre** [comment]
The torsion of the eye under natural viewing conditions is a complicated topic, and can be influenced by (e.g.) head position and vergence angle. The model includes an (optional) expression for Listing's Law, so that the pose of the eye can be specified and appropriate "pseudo" torsion applied to maintain the "true" torsion of the eye constant.

If you have an expression for what the torsion of the eye (or two eyes) should be under different viewing conditions, you can certainly get the software to display a model eye that reflects that value. The model does not, however, have code that attempts to calculate what the torsion of the eye(s) should be under varying viewing conditions (e.g., binocular viewing conditions with varying vergence angles).

Hope that helps.

**Comment by PhuDoTuong** [comment]
Thank you so much for your detailed guides.
